# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af19bbb7d4aec96d06d49aec23cb5a55dee61055e74ccd3a3ec2fb49be6ecc62186450c71f762a86be6447f4653b59a287bef3dc3b47462fe49da3a8ce08c89a

test:
  secret_key_base: f1a454dcdfe5e0e581348827aae4fee9ac536ae648d487d6f83b3bf75209097d55f74d1f665c6d70b3ac8a8b35fa4712a75f4d3ab993e6cc7de6bb5cf9fef44b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
